/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Empleado;
import Clases.Medico;
import javax.swing.JOptionPane;




/**
 *
 * @author hp
 */
public class Interfaz_Grafica extends javax.swing.JFrame {
    
    // 1. VARIABLE GLOBAL DEL SISTEMA
    private Clases.Sistema sistema;
    private Clases.Usuario usuarioLogueado;
   
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz_Grafica.class.getName());

    /**
     * Creates new form Interfaz_Grafica
     */
    public Interfaz_Grafica() {
        initComponents();
       // 1. Inicializar el sistema 
        sistema = new Clases.Sistema(100, 50, 100, 100, 20, 100, 10);
        
        // 2. Cargar los usuarios de prueba
        cargarDatosPrueba();
        
        // 3. Bloquear todos los menús 
        configurarPermisos("NINGUNO");
        
        // 4. Mostrar la pantalla de Login primero
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
        cl.show(panelPrincipal, "cardLogin");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        panelPrincipal = new javax.swing.JPanel();
        panelConsultorios = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtConsCodigo = new javax.swing.JTextField();
        txtConsEsp = new javax.swing.JTextField();
        btnConsRegistrar = new javax.swing.JButton();
        panelReportes = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        btnRepIngresos = new javax.swing.JButton();
        btnRepMedicos = new javax.swing.JButton();
        btnRepConsultorios = new javax.swing.JButton();
        panelCitas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCitaDniPaciente = new javax.swing.JTextField();
        txtCitaDniMedico = new javax.swing.JTextField();
        txtCitaFecha = new javax.swing.JTextField();
        btnAgendar = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        panelPacientes = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        panelBienvenida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAtencion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAtencion = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtAtencionMotivo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAtencionDiagnostico = new javax.swing.JTextField();
        txtAtencionTratamiento = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        panelCaja = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCaja = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtMontoPagar = new javax.swing.JTextField();
        btnCobrar = new javax.swing.JButton();
        panelEmpleados = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboEmpRol = new javax.swing.JComboBox<>();
        lblEmpEspecialidad = new javax.swing.JLabel();
        txtEmpEspecialidad = new javax.swing.JTextField();
        btnEmpRegistrar = new javax.swing.JButton();
        btnEmpEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        campoDNI = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        menuItemEmpleados = new javax.swing.JMenuItem();
        menuItemPacientes = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemCitas = new javax.swing.JMenuItem();
        menuItemAtencion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemPagos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemReportes = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Admin"); // NOI18N

        panelPrincipal.setLayout(new java.awt.CardLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("GESTION DE CONSULTORIOS");

        jLabel21.setText("CODIGO");

        jLabel22.setText("ESPECIALIDAD");

        txtConsEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsEspActionPerformed(evt);
            }
        });

        btnConsRegistrar.setText("REGISTRAR CONSULTORIO");
        btnConsRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultoriosLayout = new javax.swing.GroupLayout(panelConsultorios);
        panelConsultorios.setLayout(panelConsultoriosLayout);
        panelConsultoriosLayout.setHorizontalGroup(
            panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultoriosLayout.createSequentialGroup()
                .addGroup(panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultoriosLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel20))
                    .addGroup(panelConsultoriosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(109, 109, 109)
                        .addGroup(panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelConsultoriosLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnConsRegistrar)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        panelConsultoriosLayout.setVerticalGroup(
            panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultoriosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addGap(36, 36, 36)
                .addGroup(panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtConsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtConsEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnConsRegistrar)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelConsultorios, "cardConsultorios");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("REPORTES DE GESTIÓN");

        txtReporte.setColumns(20);
        txtReporte.setRows(5);
        jScrollPane3.setViewportView(txtReporte);

        btnRepIngresos.setText("INGRESOS TOTALES");
        btnRepIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepIngresosActionPerformed(evt);
            }
        });

        btnRepMedicos.setText("ATENCIONES POR MEDICO");
        btnRepMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepMedicosActionPerformed(evt);
            }
        });

        btnRepConsultorios.setText("ESTADO CONSULTORIOS");
        btnRepConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepConsultoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
        panelReportes.setLayout(panelReportesLayout);
        panelReportesLayout.setHorizontalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReportesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(panelReportesLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRepIngresos)
                .addGap(18, 18, 18)
                .addComponent(btnRepMedicos)
                .addGap(28, 28, 28)
                .addComponent(btnRepConsultorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReportesLayout.setVerticalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepIngresos)
                    .addComponent(btnRepMedicos)
                    .addComponent(btnRepConsultorios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        panelPrincipal.add(panelReportes, "cardReportes");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nueva Cita");

        jLabel5.setText("DNI PACIENTE");

        jLabel6.setText("DNI MEDICO");

        jLabel7.setText("FECHA");

        txtCitaDniMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitaDniMedicoActionPerformed(evt);
            }
        });

        btnAgendar.setText("AGENDAR");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCitasLayout = new javax.swing.GroupLayout(panelCitas);
        panelCitas.setLayout(panelCitasLayout);
        panelCitasLayout.setHorizontalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgendar)
                    .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCitasLayout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCitasLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCitasLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCitaDniPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCitasLayout.createSequentialGroup()
                                    .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCitaFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCitaDniMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        panelCitasLayout.setVerticalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCitaDniPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCitaDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCitaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(btnAgendar)
                .addGap(17, 17, 17))
        );

        panelPrincipal.add(panelCitas, "CITA");

        jLabel2.setText("USUARIO");

        jLabel3.setText("CONTRASEÑA");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(txtPass)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnIngresar)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelLogin, "cardLogin");

        jlabel1.setText("DNI");

        jlabel2.setText("Nombre");

        jlabel3.setText("Apellido");

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPacientesLayout = new javax.swing.GroupLayout(panelPacientes);
        panelPacientes.setLayout(panelPacientesLayout);
        panelPacientesLayout.setHorizontalGroup(
            panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel2)
                    .addComponent(jlabel3))
                .addGap(65, 65, 65)
                .addGroup(panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        panelPacientesLayout.setVerticalGroup(
            panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnGuardar)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelPacientes, "cardPacientes");

        jLabel1.setText("BIENVENIDO AL SISTEMA ");

        javax.swing.GroupLayout panelBienvenidaLayout = new javax.swing.GroupLayout(panelBienvenida);
        panelBienvenida.setLayout(panelBienvenidaLayout);
        panelBienvenidaLayout.setHorizontalGroup(
            panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBienvenidaLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        panelBienvenidaLayout.setVerticalGroup(
            panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBienvenidaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelBienvenida, "cardBienvenida");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("AGENDA DEL DÍA");

        tableAtencion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAtencion);

        jLabel9.setText("MOTIVO");

        txtAtencionMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtencionMotivoActionPerformed(evt);
            }
        });

        jLabel10.setText("DIAGNOSTICO");

        jLabel11.setText("TRATAMIENTO");

        txtAtencionDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtencionDiagnosticoActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAtencionLayout = new javax.swing.GroupLayout(panelAtencion);
        panelAtencion.setLayout(panelAtencionLayout);
        panelAtencionLayout.setHorizontalGroup(
            panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtencionLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtencionLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAtencionLayout.createSequentialGroup()
                        .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFinalizar)
                            .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAtencionTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(txtAtencionMotivo)
                                .addComponent(txtAtencionDiagnostico)))))
                .addGap(33, 33, 33))
        );
        panelAtencionLayout.setVerticalGroup(
            panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtencionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAtencionMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtencionDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panelAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAtencionTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnFinalizar)
                .addContainerGap())
        );

        panelPrincipal.add(panelAtencion, "cardAtencion");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("CAJA-PENDIENTES DE PAGO");

        tableCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCaja);

        jLabel13.setText("MONTO A PAGAR");

        txtMontoPagar.setText("0.0");
        txtMontoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoPagarActionPerformed(evt);
            }
        });

        btnCobrar.setText("GENERAR FACTURA");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCajaLayout = new javax.swing.GroupLayout(panelCaja);
        panelCaja.setLayout(panelCajaLayout);
        panelCajaLayout.setHorizontalGroup(
            panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCajaLayout.createSequentialGroup()
                .addGroup(panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCajaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel13)
                        .addGap(111, 111, 111)
                        .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajaLayout.createSequentialGroup()
                        .addComponent(btnCobrar)
                        .addGap(104, 104, 104))))
        );
        panelCajaLayout.setVerticalGroup(
            panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCajaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnCobrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelCaja, "cardCaja");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("REGISTRO DE PERSONAL");

        jLabel15.setText("DNI");

        jLabel16.setText("NOMBRE");

        jLabel17.setText("APELLIDO");

        cboEmpRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEDICO", "RECEPCIONISTA", "CAJERO", "ADMINISTRADOR" }));
        cboEmpRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmpRolActionPerformed(evt);
            }
        });

        lblEmpEspecialidad.setText("ESPECIALIDAD");

        txtEmpEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpEspecialidadActionPerformed(evt);
            }
        });

        btnEmpRegistrar.setText("REGISTRAR EMPLEADO");
        btnEmpRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpRegistrarActionPerformed(evt);
            }
        });

        btnEmpEliminar.setText("ELIMINAR EMPLEADO");
        btnEmpEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpEliminarActionPerformed(evt);
            }
        });

        jButton1.setText("MODIFICAR EMPLEADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboEmpRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(lblEmpEspecialidad))
                                                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                                        .addGap(112, 112, 112)
                                                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txtEmpEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnEmpRegistrar)
                                        .addGap(33, 33, 33)))
                                .addComponent(btnEmpEliminar)))))
                .addGap(18, 18, 18))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboEmpRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel16))
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpEspecialidad)
                    .addComponent(txtEmpEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpRegistrar)
                    .addComponent(btnEmpEliminar)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        panelPrincipal.add(panelEmpleados, "cardEmpleados");

        jMenu5.setText("Funciones");

        menuItemEmpleados.setText("Empleados");
        menuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpleadosActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemEmpleados);

        menuItemPacientes.setText("Pacientes");
        menuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPacientesActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemPacientes);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Consultorios");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem1);

        jMenuItem1.setText("Cerrar sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar3.add(jMenu5);

        jMenu6.setText("Atención");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        menuItemCitas.setText("Citas medicas");
        menuItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCitasActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemCitas);

        menuItemAtencion.setText("Atender consulta");
        menuItemAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAtencionActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemAtencion);

        jMenuBar3.add(jMenu6);

        jMenu3.setText("Caja");

        menuItemPagos.setText("Facturación y pagos");
        menuItemPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPagosActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemPagos);

        jMenuBar3.add(jMenu3);

        jMenu4.setText("Reportes");

        menuItemReportes.setSelected(true);
        menuItemReportes.setText("Ver Reportes");
        menuItemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReportesActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemReportes);

        jMenuBar3.add(jMenu4);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPacientesActionPerformed
        // TODO add your handling code here:
        // Ocultar bienvenida y mostrar formulario de pacientes
    java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
    cl.show(panelPrincipal, "cardPacientes");
    }//GEN-LAST:event_menuItemPacientesActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Recoger datos
    String dni = txtDNI.getText();
    String nombre = txtNombre.getText();
    String apellido = txtApellido.getText();
    
    if (dni.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Llene todo por favor.");
        return;
    }
    
    // Guardar
    Clases.Paciente nuevo = new Clases.Paciente(dni, nombre, apellido, "S/T", "S/E", 2000, "M", "S/D", "S/C");
    if (sistema.getGestionPaciente().agregar(nuevo)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Guardado!");
        txtDNI.setText(""); txtNombre.setText(""); txtApellido.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        //Capturar lo que escribió el usuario
    String u = txtUser.getText();
    String p = new String(txtPass.getPassword());
    
    //Validar que no estén vacíos
    if (u.isEmpty() || p.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor escriba usuario y contraseña");
        return;
    }
    
    //Preguntar al Sistema si el usuario existe
    Clases.Usuario encontrado = sistema.login(u, p);
    
    if (encontrado != null) {
        // --- CASO ÉXITO: EL USUARIO EXISTE ---
        usuarioLogueado = encontrado;
        
        //Mensaje de bienvenida
        javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido: " + encontrado.getRol());
        
        //Activar los menús que le tocan a este rol
        configurarPermisos(encontrado.getRol());
        
        //Quitar la pantalla de Login y mostrar la de Bienvenida
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
        cl.show(panelPrincipal, "cardBienvenida");
        
        //Limpiar los campos por si cierran sesión luego
        txtUser.setText("");
        txtPass.setText("");
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Usuario o clave incorrectos.");
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // Recoger datos y limpiarlos 
    // --- AQUÍ PEGAS EL CÓDIGO CHISMOSO ---
    System.out.println("=== LISTA DE EMPLEADOS EN MEMORIA ===");
    for (Clases.Empleado emp : sistema.getGestionEmpleado().getEmpleados()) {
        if (emp != null) {
            System.out.println("DNI: " + emp.getDni() + 
                               " | Nombre: " + emp.getNombres() + 
                               " | Clase: " + emp.getClass().getSimpleName()); // Esto te dirá si es Medico o Recepcionista
        }
    }
    System.out.println("=====================================");
    // -------------------------------------

    String dniPac = txtCitaDniPaciente.getText().trim(); 
    String dniMed = txtCitaDniMedico.getText().trim(); 
    String fecha = txtCitaFecha.getText();

    //Validar que no estén vacíos
    if (dniPac.isEmpty() || dniMed.isEmpty() || fecha.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los datos.");
        return;
    }

    //BUSCAMOS AL PACIENTE Y AL MÉDICO (CÓDIGO MEJORADO)
    Clases.Paciente pacienteEncontrado = null;
    Clases.Medico medicoEncontrado = null;

    //Búsqueda del Paciente 
    for (Clases.Paciente p : sistema.getGestionPaciente().getPacientes()) {
        if (p != null && p.getDni().trim().equals(dniPac)) {
            pacienteEncontrado = p;
            break;
        }
    }

    //BÚSQUEDA ROBUSTA DEL MÉDICO 
    int totalEmpleados = sistema.getGestionEmpleado().getCantidad();
    
    for (int i = 0; i < totalEmpleados; i++) {
        // Obtenemos el empleado de la posición 'i'
        Clases.Empleado e = sistema.getGestionEmpleado().getEmpleados()[i];

        // Verificamos que sea un Médico y que el DNI coincida
        if (e instanceof Clases.Medico) {
            
            // Comparamos el DNI del empleado con el DNI buscado
            if (e.getDni().trim().equals(dniMed)) { 
                medicoEncontrado = (Clases.Medico) e;
                break;
            }
        }
    }
    
    //Validar si los encontramos
    if (pacienteEncontrado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Paciente no encontrado. Regístrelo primero.");
        return;
    }
    if (medicoEncontrado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Médico no encontrado (Revise el DNI).");
        return;
    }

    //Crear la Cita
    Clases.Consultorio consultorio = new Clases.Consultorio("101", "General", "DISPONIBLE");
    String codigoCita = "C-" + (sistema.getGestionCita().getCantidad() + 1);
    
    Clases.Cita nuevaCita = new Clases.Cita(
            codigoCita, 
            fecha, 
            "PROGRAMADA", 
            pacienteEncontrado, 
            medicoEncontrado, 
            consultorio
    );

    //Guardar y Confirmar
    if (sistema.getGestionCita().agregar(nuevaCita)) {
        String mensaje = "¡Cita Agendada con Éxito!\n\n" +
                         "Código: " + codigoCita + "\n" +
                         "Paciente: " + pacienteEncontrado.getNombreCompleto() + "\n" +
                         "Atiende: " + medicoEncontrado.getNombreCompleto() + "\n" +
                         "Fecha: " + fecha;
                         
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
        
        // Limpiar campos para la siguiente
        txtCitaDniPaciente.setText("");
        txtCitaDniMedico.setText("");
        txtCitaFecha.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: La agenda está llena, no caben más citas.");
    }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
        // Cambiar a la pantalla de Citas
        System.out.println("¡CLICK EN EL MENÚ RECIBIDO!"); 
    java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
    cl.show(panelPrincipal, "CITA");
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void menuItemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCitasActionPerformed
        // TODO add your handling code here:

    //Cambiar la carta
    java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
    
    cl.show(panelPrincipal, "CITA");
    }//GEN-LAST:event_menuItemCitasActionPerformed

    private void menuItemAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAtencionActionPerformed
        // TODO add your handling code here:
        //Cambiar a la pantalla de Atención
    java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
    cl.show(panelPrincipal, "cardAtencion");
    
    //Cargar la lista de pacientes
    cargarCitasDelMedico();
    }//GEN-LAST:event_menuItemAtencionActionPerformed

    private void txtAtencionDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtencionDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtencionDiagnosticoActionPerformed

    private void txtAtencionMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtencionMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtencionMotivoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        // Verificar si seleccionó a alguien en la tabla
    int fila = tableAtencion.getSelectedRow();
    
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Ojo! Primero selecciona una cita de la tabla.");
        return;
    }
    
    //Obtener el código de la cita
    String codigoCita = tableAtencion.getValueAt(fila, 0).toString();
    
    // Buscar esa cita
    Clases.Cita citaReal = null;
    for (Clases.Cita c : sistema.getGestionCita().getCitas()) {
        if (c != null && c.getCodigo().equals(codigoCita)) {
            citaReal = c;
            break;
        }
    }
    
    if (citaReal != null) {
        // CAMBIAR ESTADO 
        citaReal.setEstado("ATENDIDA");
        
        // Mensaje y Limpieza
        javax.swing.JOptionPane.showMessageDialog(this, "¡Listo! Paciente atendido.");
        
        txtAtencionMotivo.setText("");
        txtAtencionDiagnostico.setText("");
        txtAtencionTratamiento.setText("");
        
        cargarCitasDelMedico();
    }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // Borrar el usuario actual
    usuarioLogueado = null;
    
    // Bloquear menús de nuevo
    configurarPermisos("NINGUNO");
    
    // Volver a la pantalla de Login
    java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
    cl.show(panelPrincipal, "cardLogin");
    
    // Limpiar campos de login
    txtUser.setText("");
    txtPass.setText("");
    
    javax.swing.JOptionPane.showMessageDialog(this, "Sesión Cerrada.");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPagosActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
    cl.show(panelPrincipal, "cardCaja");
    
    // Cargar la tabla de cobros al entrar
    cargarCitasPorCobrar();
    }//GEN-LAST:event_menuItemPagosActionPerformed

    private void txtMontoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoPagarActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        // TODO add your handling code here:
        int fila = tableCaja.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cita para cobrar");
        return;
    }
    
    String codCita = tableCaja.getValueAt(fila, 0).toString();
    
    // Buscar la cita real
    Clases.Cita citaReal = null;
    for(Clases.Cita c : sistema.getGestionCita().getCitas()){
        if(c != null && c.getCodigo().equals(codCita)){
            citaReal = c; break;
        }
    }
    
    if (citaReal != null) {
        // Cambiamos el estado a PAGADA 
        citaReal.setEstado("PAGADA");
        // 1. Convertir el texto de la caja a número
    double dinero = Double.parseDouble(txtMontoPagar.getText());
    
    // 2. Guardarlo en la cita (Usando el método nuevo que creamos)
    citaReal.setMontoPagado(dinero);
            
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Pago registrado! Factura generada.");
        cargarCitasPorCobrar(); 
    }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void menuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpleadosActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
cl.show(panelPrincipal, "cardEmpleados");

    }//GEN-LAST:event_menuItemEmpleadosActionPerformed

    private void txtEmpEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpEspecialidadActionPerformed

    private void btnEmpRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpRegistrarActionPerformed
  // Recoger datos
    String dni = campoDNI.getText().trim();
    String nom = campoNombre.getText();
    String ape = campoApellido.getText();
    String especialidad = txtEmpEspecialidad.getText(); 
    
    // Obtener y LIMPIAR el rol
    String rol = "";
    if (cboEmpRol.getSelectedItem() != null) {
        rol = cboEmpRol.getSelectedItem().toString();
        rol = rol.trim();
    }

    // Validaciones
    if (dni.isEmpty() || nom.isEmpty() || ape.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe completar DNI, Nombre y Apellido.");
        return;
    }
    
    if (rol.equalsIgnoreCase("MÉDICO") && especialidad.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El rol Médico requiere una Especialidad.");
        return;
    }

    //POLIMORFISMO: Crear el objeto correcto
    Clases.Empleado nuevoEmpleado = null;
    Clases.Usuario nuevoUsuario = null;
    String codigoEmp = "E-" + (sistema.getGestionEmpleado().getCantidad() + 1);
    

    if (rol.equalsIgnoreCase("MEDICO") || rol.equalsIgnoreCase("MÉDICO")) {
        nuevoEmpleado = new Clases.Medico(codigoEmp, dni, nom, ape, "999", "mail", especialidad);
        nuevoUsuario = new Clases.Usuario(dni, "1234", "MEDICO", nuevoEmpleado);
        
    } else if (rol.equalsIgnoreCase("RECEPCIONISTA")) {
        nuevoEmpleado = new Clases.Recepcionista(codigoEmp, dni, nom, ape, "888", "mail");
        nuevoUsuario = new Clases.Usuario(dni, "1234", "RECEPCIONISTA", nuevoEmpleado);
        
    } else if (rol.equalsIgnoreCase("CAJERO")) {
        nuevoEmpleado = new Clases.Cajero(codigoEmp, dni, nom, ape, "666", "mail");
        nuevoUsuario = new Clases.Usuario(dni, "1234", "CAJERO", nuevoEmpleado);
        
    } else if (rol.equalsIgnoreCase("ADMINISTRADOR")) {
        nuevoEmpleado = new Clases.Administrador(
            sistema.getGestionEmpleado(), sistema.getGestionConsultorio(), sistema.getGestionConsulta(),
            codigoEmp, dni, nom, ape, "777", "mail");
        nuevoUsuario = new Clases.Usuario(dni, "1234", "ADMINISTRADOR", nuevoEmpleado);
    }
    
    //Guardar y notificar
    if (nuevoEmpleado != null) {
        if (sistema.getGestionEmpleado().agregar(nuevoEmpleado) && sistema.agregarUsuario(nuevoUsuario)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Empleado Registrado!\nRol: " + rol + "\nUsuario: " + dni + "\nClave: 1234");
            // Limpiar
            campoNombre.setText("");
            campoApellido.setText("");
            campoDNI.setText("");
            txtEmpEspecialidad.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de Memoria: El empleado ya existe o la lista está llena.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Rol no válido o no seleccionado."); 
    }
    }//GEN-LAST:event_btnEmpRegistrarActionPerformed

    private void menuItemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReportesActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
cl.show(panelPrincipal, "cardReportes");
    }//GEN-LAST:event_menuItemReportesActionPerformed

    private void btnRepIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepIngresosActionPerformed
        // TODO add your handling code here:
        double total = 0;
    int cantidad = 0;
    txtReporte.setText("=== REPORTE DE INGRESOS ===\n\n");
    
    // Recorremos las citas
    for(Clases.Cita c : sistema.getGestionCita().getCitas()) {
        if(c != null && c.getEstado().equals("PAGADA")) {
            // Buscamos cuánto costó la consulta asociada
            total += c.getMontoPagado(); 
            cantidad++;
        }
    }
    txtReporte.append("Citas Cobradas: " + cantidad + "\n");
    txtReporte.append("Total Recaudado: S/. " + total);
    }//GEN-LAST:event_btnRepIngresosActionPerformed

    private void btnRepMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepMedicosActionPerformed
        // TODO add your handling code here:
        txtReporte.setText("=== PRODUCTIVIDAD MÉDICA ===\n\n");
    
    // Recorremos todos los empleados que sean médicos
    for(Clases.Empleado e : sistema.getGestionEmpleado().getEmpleados()) {
        if(e != null && e instanceof Clases.Medico) {
            int contador = 0;
            // Contamos sus citas atendidas
            for(Clases.Cita c : sistema.getGestionCita().getCitas()) {
                if(c != null && c.getMedico().getDni().equals(e.getDni()) 
                   && (c.getEstado().equals("ATENDIDA") || c.getEstado().equals("PAGADA"))) {
                    contador++;
                }
            }
            txtReporte.append("Dr. " + e.getApellidos() + ": " + contador + " atenciones.\n");
        }
    }
    }//GEN-LAST:event_btnRepMedicosActionPerformed

    private void btnRepConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepConsultoriosActionPerformed
        // TODO add your handling code here:
        txtReporte.setText("=== ESTADO DE CONSULTORIOS ===\n\n");
    for(Clases.Consultorio c : sistema.getGestionConsultorio().getConsultorios()) {
        if(c != null) {
            txtReporte.append("Consultorio " + c.getCodigo() + " [" + c.getEspecialidad() + "] -> " + c.getEstado() + "\n");
        }
    }
    }//GEN-LAST:event_btnRepConsultoriosActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout)(panelPrincipal.getLayout());
cl.show(panelPrincipal, "cardConsultorios");
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void txtConsEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsEspActionPerformed

    private void btnConsRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsRegistrarActionPerformed
        // TODO add your handling code here:
        String codigo = txtConsCodigo.getText();
    String esp = txtConsEsp.getText();
    
    if(codigo.isEmpty() || esp.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Complete los datos");
        return;
    }
    
    // Crear Consultorio
    Clases.Consultorio nuevo = new Clases.Consultorio(codigo, esp, "DISPONIBLE");
    
    if(sistema.getGestionConsultorio().agregar(nuevo)){
        javax.swing.JOptionPane.showMessageDialog(this, "¡Consultorio Creado!");
        txtConsCodigo.setText("");
        txtConsEsp.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Memoria llena o código repetido");
    }
    }//GEN-LAST:event_btnConsRegistrarActionPerformed

    private void cboEmpRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmpRolActionPerformed
    String rolSeleccionado = cboEmpRol.getSelectedItem().toString();
    
    boolean esMedico = rolSeleccionado.equalsIgnoreCase("MÉDICO");
    
    // Ocultar/Mostrar el CAMPO DE TEXTO
    txtEmpEspecialidad.setVisible(esMedico);

    // Ocultar/Mostrar la ETIQUETA DE ESPECIALIDAD
    if (lblEmpEspecialidad != null) { 
        lblEmpEspecialidad.setVisible(esMedico);
    }

    panelEmpleados.revalidate(); 
    panelEmpleados.repaint();
        
    }//GEN-LAST:event_cboEmpRolActionPerformed

    private void txtCitaDniMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitaDniMedicoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCitaDniMedicoActionPerformed

    private void btnEmpEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpEliminarActionPerformed
        // TODO add your handling code here:
        // Lógica para ELIMINAR EMPLEADO
    
    // Pedir el DNI a través de un cuadro de diálogo
    String dniAEliminar = javax.swing.JOptionPane.showInputDialog(
            this,
            "Ingrese el DNI del empleado a eliminar:",
            "Eliminar Empleado",
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    
    // Si el usuario da Cancelar o no ingresa nada, salimos
    if (dniAEliminar == null || dniAEliminar.trim().isEmpty()) {
        return;
    }
    
    // Limpiar el DNI
    dniAEliminar = dniAEliminar.trim();
    
    // Confirmación
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de eliminar al empleado con DNI " + dniAEliminar + "? Esta acción es irreversible.",
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        // 3. Llamar a la lógica de eliminación
        if (sistema.getGestionEmpleado().eliminar(dniAEliminar)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Empleado " + dniAEliminar + " eliminado con éxito!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encontró un empleado con ese DNI.");
        }
    }
    }//GEN-LAST:event_btnEmpEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// 1. Pedir el DNI a buscar mediante una ventanita
    String dniBuscado = javax.swing.JOptionPane.showInputDialog("Ingrese el DNI del empleado a modificar:");
    
    // Si el usuario cancela o lo deja vacío, salimos
    if (dniBuscado == null || dniBuscado.trim().isEmpty()) {
        return;
    }

    // 2. Buscar al empleado en la memoria
    Clases.Empleado empEncontrado = sistema.getGestionEmpleado().buscarEmpleadoPorDni(dniBuscado.trim());

    if (empEncontrado != null) {
        // --- SI LO ENCONTRAMOS, PEDIMOS LOS DATOS NUEVOS ---
        
        // Pedir Nuevo Nombre (Mostrando el actual para que sea fácil editar)
        String nuevoNombre = javax.swing.JOptionPane.showInputDialog("Ingrese el Nuevo Nombre:", empEncontrado.getNombres());
        
        // Pedir Nuevo Apellido
        String nuevoApellido = javax.swing.JOptionPane.showInputDialog("Ingrese el Nuevo Apellido:", empEncontrado.getApellidos());
        
        // Si es MEDICO, pedimos especialidad también
        if (empEncontrado instanceof Clases.Medico) {
             Clases.Medico medicoReal = (Clases.Medico) empEncontrado;
             String nuevaEsp = javax.swing.JOptionPane.showInputDialog("Nueva Especialidad:", medicoReal.getEspecialidad());
             if (nuevaEsp != null && !nuevaEsp.isEmpty()) {
                 medicoReal.setEspecialidad(nuevaEsp);
             }
        }

        // 3. Guardar los cambios si el usuario escribió algo
        if (nuevoNombre != null && !nuevoNombre.isEmpty()) {
            empEncontrado.setNombres(nuevoNombre);
        }
        if (nuevoApellido != null && !nuevoApellido.isEmpty()) {
            empEncontrado.setApellidos(nuevoApellido);
        }

        javax.swing.JOptionPane.showMessageDialog(this, "¡Datos actualizados correctamente!");
        
    } else {
        // --- SI NO EXISTE ---
        javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encontró ningún empleado con DNI " + dniBuscado);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz_Grafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnConsRegistrar;
    private javax.swing.JButton btnEmpEliminar;
    private javax.swing.JButton btnEmpRegistrar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRepConsultorios;
    private javax.swing.JButton btnRepIngresos;
    private javax.swing.JButton btnRepMedicos;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> cboEmpRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel lblEmpEspecialidad;
    private javax.swing.JMenuItem menuItemAtencion;
    private javax.swing.JMenuItem menuItemCitas;
    private javax.swing.JMenuItem menuItemEmpleados;
    private javax.swing.JMenuItem menuItemPacientes;
    private javax.swing.JMenuItem menuItemPagos;
    private javax.swing.JCheckBoxMenuItem menuItemReportes;
    private javax.swing.JPanel panelAtencion;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelCaja;
    private javax.swing.JPanel panelCitas;
    private javax.swing.JPanel panelConsultorios;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JTable tableAtencion;
    private javax.swing.JTable tableCaja;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAtencionDiagnostico;
    private javax.swing.JTextField txtAtencionMotivo;
    private javax.swing.JTextField txtAtencionTratamiento;
    private javax.swing.JTextField txtCitaDniMedico;
    private javax.swing.JTextField txtCitaDniPaciente;
    private javax.swing.JTextField txtCitaFecha;
    private javax.swing.JTextField txtConsCodigo;
    private javax.swing.JTextField txtConsEsp;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEmpEspecialidad;
    private javax.swing.JTextField txtMontoPagar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextArea txtReporte;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void configurarPermisos(String rol) {
      //Ocultar todo al inicio
        menuItemEmpleados.setVisible(false);
        menuItemPacientes.setVisible(false);
        menuItemCitas.setVisible(false);
        
        if (menuItemAtencion != null) menuItemAtencion.setVisible(false);
        if (menuItemPagos != null) menuItemPagos.setVisible(false);
        // -------------------------------------------

        // Mostrar según rol
        if (rol.equalsIgnoreCase("ADMINISTRADOR")) {
            menuItemEmpleados.setVisible(true);
            
        } else if (rol.equalsIgnoreCase("RECEPCIONISTA")) {
            menuItemPacientes.setVisible(true);
            menuItemCitas.setVisible(true);
            if (menuItemPagos != null) menuItemPagos.setVisible(true); 

        } else if (rol.equalsIgnoreCase("MEDICO")) {
            if (menuItemAtencion != null) menuItemAtencion.setVisible(true); 
        }
    }
    private void cargarDatosPrueba() {
        // Crear un ADMINISTRADOR (Usuario: admin / Clave: 1234)
        Clases.Administrador adm = new Clases.Administrador(
            sistema.getGestionEmpleado(), sistema.getGestionConsultorio(), sistema.getGestionConsulta(),
            "ADM01", "1111", "Juan", "Perez", "999", "admin@mail.com");
        
        sistema.getGestionEmpleado().agregar(adm);
        sistema.agregarUsuario(new Clases.Usuario("admin", "1234", "ADMINISTRADOR", adm));

        // Crear una RECEPCIONISTA (Usuario: recep / Clave: 1234)
        Clases.Recepcionista recep = new Clases.Recepcionista(
            "REC01", "2222", "Ana", "Gomez", "888", "ana@mail.com");
        
        sistema.getGestionEmpleado().agregar(recep);
        sistema.agregarUsuario(new Clases.Usuario("recep", "1234", "RECEPCIONISTA", recep));
        
        // Crear un MÉDICO (Usuario: medico / Clave: 1234)
       Clases.Medico med = new Clases.Medico(
            "MED01", "9090", "Dra. Laura", "Salas", "777", "laura@mail.com", "Pediatría");
        
        sistema.getGestionEmpleado().agregar(med);
        sistema.agregarUsuario(new Clases.Usuario("9090", "1234", "MEDICO", med)); 
    }
    // MÉTODO PARA LLENAR LA TABLA DEL MÉDICO
    private void cargarCitasDelMedico() {
        // Definir modelo de tabla
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Código Cita");
        modelo.addColumn("Fecha");
        modelo.addColumn("Paciente");
        modelo.addColumn("Estado");
        
        // Buscar citas que sean de ESTE médico logueado
        if (usuarioLogueado != null && usuarioLogueado.getRol().equals("MEDICO")) {
            String dniMedicoLogueado = usuarioLogueado.getEmpleado().getDni();
            
            Clases.Cita[] lista = sistema.getGestionCita().getCitas();
            int cantidad = sistema.getGestionCita().getCantidad();
            
            for (int i = 0; i < cantidad; i++) {
                if (lista[i].getMedico().getDni().equals(dniMedicoLogueado) && 
                   !lista[i].getEstado().equals("ATENDIDA")) {
                    
                    modelo.addRow(new Object[]{
                        lista[i].getCodigo(),
                        lista[i].getFechaHora(),
                        lista[i].getPaciente().getNombreCompleto(),
                        lista[i].getEstado()
                    });
                }
            }
        }
        tableAtencion.setModel(modelo);
        
    }
    private void cargarCitasPorCobrar() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Cód Cita");
        modelo.addColumn("Paciente");
        modelo.addColumn("Médico");
        modelo.addColumn("Estado");
        
        Clases.Cita[] lista = sistema.getGestionCita().getCitas();
        
        for (int i = 0; i < sistema.getGestionCita().getCantidad(); i++) {
            if (lista[i].getEstado().equals("ATENDIDA")) {
                modelo.addRow(new Object[]{
                    lista[i].getCodigo(),
                    lista[i].getPaciente().getNombreCompleto(),
                    lista[i].getMedico().getNombreCompleto(),
                    lista[i].getEstado()
                });
            }
        }
        tableCaja.setModel(modelo);
    }

}
